project:
  type: website
  output-dir: docs

website:
  title: "Vanessa Ragan"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    right:
      - href: final_project.qmd
        text: Final Project
        #icon: megaphone
    tools:
      - icon: github
        href: github.com
      
format:
  html:
    backgroundcolor: "#eeffff"
    fontcolor: "darkblue"
    linkcolor: "black"
    mainfont: "sarif"
    fontsize: 20px
    theme: [cosmo, styles.scss]

